require('plugins.mini')
require('plugins.alpha')
require('plugins.snacks')

require('plugins.blink')
require('plugins.conform')
require('plugins.crates-nvim')
require('plugins.gitsigns')
require('plugins.multicursor')
require('plugins.rustaceanvim')
require('plugins.tmux')
require('plugins.todo-comments')
